name: Unit Tests

on:
  pull_request:
    branches:
        - main

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ROS 2 workspace
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distro: humble

    - name: Build and test
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: fogros2_rt_x
        target-ros2-distro: humble